/* GET SALES_ORDER_LIST */
export const GET_SALES_ORDER_LIST = "GET_SALES_ORDER_LIST";
export const GET_SALES_ORDER_LIST_SUCCESS = "GET_SALES_ORDER_LIST_SUCCESS";
export const GET_SALES_ORDER_LIST_FAIL = "GET_SALES_ORDER_LIST_FAIL";

/* ADD SALES_ORDER_LIST */
export const ADD_NEW_SALES_ORDER_LIST = "ADD_NEW_SALES_ORDER_LIST";
export const ADD_NEW_SALES_ORDER_LIST_SUCCESS = "ADD_NEW_SALES_ORDER_LIST_SUCCESS";
export const ADD_NEW_SALES_ORDER_LIST_FAIL = "ADD_NEW_SALES_ORDER_LIST_FAIL";

/* EDIT SALES_ORDER_LIST */
export const UPDATE_SALES_ORDER_LIST = "UPDATE_SALES_ORDER_LIST";
export const UPDATE_SALES_ORDER_LIST_SUCCESS = "UPDATE_SALES_ORDER_LIST_SUCCESS";
export const UPDATE_SALES_ORDER_LIST_FAIL = "UPDATE_SALES_ORDER_LIST_FAIL";

/* DELETE SALES_ORDER_LIST */
export const DELETE_SALES_ORDER_LIST = "DELETE_SALES_ORDER_LIST";
export const DELETE_SALES_ORDER_LIST_SUCCESS = "DELETE_SALES_ORDER_LIST_SUCCESS";
export const DELETE_SALES_ORDER_LIST_FAIL = "DELETE_SALES_ORDER_LIST_FAIL";

export const UPDATE_SALES_ORDER_STATUS = "UPDATE_SALES_ORDER_STATUS";
export const UPDATE_SALES_ORDER_STATUS_SUCCESS = "UPDATE_SALES_ORDER_STATUS_SUCCESS";
export const UPDATE_SALES_ORDER_STATUS_FAIL = "UPDATE_SALES_ORDER_STATUS_FAIL";

export const CLEAR_SALES_ORDER_LIST = "CLEAR_SALES_ORDER_LIST";
