export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const API_ERROR = "LOGIN_API_ERROR";

export const LOGIN_WITH_AZURE = "LOGIN_WITH_AZURE";
export const LOGIN_WITH_AZURE_SUCCESS = "LOGIN_WITH_AZURE_SUCCESS";
export const LOGIN_WITH_AZURE_ERROR = "LOGIN_WITH_AZURE_ERROR";

export const AZURE_LOGIN = "AZURE_LOGIN_RESPONSE";
export const AZURE_LOGIN_SUCCESS = "AZURE_LOGIN_SUCCESS";
export const AZURE_LOGIN_ERROR = "AZURE_LOGIN_ERROR";
