/* ADD CONTACT */
export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
export const ADD_NEW_CONTACT_SUCCESS = "ADD_NEW_CONTACT_SUCCESS";
export const ADD_NEW_CONTACT_FAIL = "ADD_NEW_CONTACT_FAIL";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";

export const CLEAR_IMAGE = "CLEAR_IMAGE";

export const CLEAR_ALL_IMAGE = "CLEAR_ALL_IMAGE";

export const GET_ALL_CONTACT = "GET_ALL_CONTACT";
export const GET_ALL_CONTACT_SUCCESS = "GET_ALL_CONTACT_SUCCESS";
export const GET_ALL_CONTACT_FAIL = "GET_ALL_CONTACT_FAIL";

export const GET_CONTACT_DETAILS = "GET_CONTACT_DETAILS";
export const GET_CONTACT_DETAILS_SUCCESS = "GET_CONTACT_DETAILS_SUCCESS";
export const GET_CONTACT_DETAILS_FAIL = "GET_CONTACT_DETAILS_FAIL";
