/* GET TOTAL_ORDERS */
export const GET_TOTAL_ORDERS = "GET_TOTAL_ORDERS";
export const GET_TOTAL_ORDERS_SUCCESS = "GET_TOTAL_ORDERS_SUCCESS";
export const GET_TOTAL_ORDERS_FAIL = "GET_TOTAL_ORDERS_FAIL";

/* GET OPEN_ORDERS */
export const GET_OPEN_ORDERS = "GET_OPEN_ORDERS";
export const GET_OPEN_ORDERS_SUCCESS = "GET_OPEN_ORDERS_SUCCESS";
export const GET_OPEN_ORDERS_FAIL = "GET_OPEN_ORDERS_FAIL";

/* GET CANCEL_ORDERS */
export const GET_CANCEL_ORDERS = "GET_CANCEL_ORDERS";
export const GET_CANCEL_ORDERS_SUCCESS = "GET_CANCEL_ORDERS_SUCCESS";
export const GET_CANCEL_ORDERS_FAIL = "GET_CANCEL_ORDERS_FAIL";

/* GET ORDERS_PAYMENT */
export const GET_TOTAL_ORDERS_PAYMENT = "GET_TOTAL_ORDERS_PAYMENT";
export const GET_TOTAL_ORDERS_PAYMENT_SUCCESS = "GET_TOTAL_ORDERS_PAYMENT_SUCCESS";
export const GET_TOTAL_ORDERS_PAYMENT_FAIL = "GET_TOTAL_ORDERS_PAYMENT_FAIL";

/* GET TOP PRODUCTS */
export const GET_TOP_PRODUCTS = "GET_TOP_PRODUCTS";
export const GET_TOP_PRODUCTS_SUCCESS = "GET_TOP_PRODUCTS_SUCCESS";
export const GET_TOP_PRODUCTS_FAIL = "GET_TOP_PRODUCTS_FAIL";

/* GET SALES ORDER REPORT */
export const GET_SELL_ORDER_REPORT = "GET_SELL_ORDER_REPORT";
export const GET_SELL_ORDER_REPORT_SUCCESS = "GET_SELL_ORDER_REPORT_SUCCESS";
export const GET_SELL_ORDER_REPORT_FAIL = "GET_SELL_ORDER_REPORT_FAIL";

/* GET MONTHLY ORDER REPORT */
export const GET_MONTHLY_ORDER_REPORT = "GET_MONTHLY_ORDER_REPORT";
export const GET_MONTHLY_ORDER_REPORT_SUCCESS = "GET_MONTHLY_ORDER_REPORT_SUCCESS";
export const GET_MONTHLY_ORDER_REPORT_FAIL = "GET_MONTHLY_ORDER_REPORT_FAIL";
