/* GET PRODUCT_LIST */

export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAIL = "GET_PRODUCT_LIST_FAIL";

/* ADD PRODUCT_LIST */
export const ADD_NEW_PRODUCT_LIST = "ADD_NEW_PRODUCT_LIST";
export const ADD_NEW_PRODUCT_LIST_SUCCESS = "ADD_NEW_PRODUCT_LIST_SUCCESS";
export const ADD_NEW_PRODUCT_LIST_FAIL = "ADD_NEW_PRODUCT_LIST_FAIL";

/* EDIT PRODUCT_LIST */
export const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
export const UPDATE_PRODUCT_LIST_SUCCESS = "UPDATE_PRODUCT_LIST_SUCCESS";
export const UPDATE_PRODUCT_LIST_FAIL = "UPDATE_PRODUCT_LIST_FAIL";

/* DELETE PRODUCT_LIST */
export const DELETE_PRODUCT_LIST = "DELETE_PRODUCT_LIST";
export const DELETE_PRODUCT_LIST_SUCCESS = "DELETE_PRODUCT_LIST_SUCCESS";
export const DELETE_PRODUCT_LIST_FAIL = "DELETE_PRODUCT_LIST_FAIL";

export const UPLOAD_PRODUCT_IMAGE = "UPLOAD_PRODUCT_IMAGE";
export const UPLOAD_PRODUCT_IMAGE_SUCCESS = "UPLOAD_PRODUCT_IMAGE_SUCCESS";
export const UPLOAD_PRODUCT_IMAGE_FAIL = "UPLOAD_PRODUCT_IMAGE_FAIL";

export const CLEAR_PRODUCT_IMAGES = "CLEAR_PRODUCT_IMAGES";

export const CLEAR_SINGLE_IMAGE = "CLEAR_SINGLE_IMAGE";

export const QUANTITY_CHANGE = "QUANTITY_CHANGE";

export const CLEAR_CART = "CLEAR_CART";

export const ADD_TO_CART = "ADD_TO_CART";

export const RESET_STATUS = "RESET_STATUS";
