/* GET TRANSACTION_HISTORY */
export const GET_TRANSACTION_HISTORY = "GET_TRANSACTION_HISTORY";
export const GET_TRANSACTION_HISTORY_SUCCESS = "GET_TRANSACTION_HISTORY_SUCCESS";
export const GET_TRANSACTION_HISTORY_FAIL = "GET_TRANSACTION_HISTORY_FAIL";

/* ADD TRANSACTION_HISTORY */
export const ADD_NEW_TRANSACTION_HISTORY = "ADD_NEW_TRANSACTION_HISTORY";
export const ADD_NEW_TRANSACTION_HISTORY_SUCCESS = "ADD_NEW_TRANSACTION_HISTORY_SUCCESS";
export const ADD_NEW_TRANSACTION_HISTORY_FAIL = "ADD_NEW_TRANSACTION_HISTORY_FAIL";

/* EDIT TRANSACTION_HISTORY */
export const UPDATE_TRANSACTION_HISTORY = "UPDATE_TRANSACTION_HISTORY";
export const UPDATE_TRANSACTION_HISTORY_SUCCESS = "UPDATE_TRANSACTION_HISTORY_SUCCESS";
export const UPDATE_TRANSACTION_HISTORY_FAIL = "UPDATE_TRANSACTION_HISTORY_FAIL";

/* DELETE TRANSACTION_HISTORY */
export const DELETE_TRANSACTION_HISTORY = "DELETE_TRANSACTION_HISTORY";
export const DELETE_TRANSACTION_HISTORY_SUCCESS = "DELETE_TRANSACTION_HISTORY_SUCCESS";
export const DELETE_TRANSACTION_HISTORY_FAIL = "DELETE_TRANSACTION_HISTORY_FAIL";

/* EXPORT TOTAL TRANSACTIONS */
export const EXPORT_TOTAL_TRANSACTIONS = "EXPORT_TOTAL_TRANSACTIONS";
export const EXPORT_TOTAL_TRANSACTIONS_SUCCESS = "EXPORT_TOTAL_TRANSACTIONS_SUCCESS";
export const EXPORT_TOTAL_TRANSACTIONS_FAIL = "EXPORT_TOTAL_TRANSACTIONS_FAIL";

export const SAVE_INVOICE_FILTERS = "SAVE_INVOICE_FILTERS";
